version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cvadmin
      POSTGRES_PASSWORD: cvpass
      POSTGRES_DB: cvdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://cvadmin:cvpass@postgres:5432/cvdb

volumes:
  postgres_data:
